// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"sheepim-auth-service/biz/infra/config"
	"sheepim-auth-service/biz/internal/service"
)

// Injectors from wire.go:

func GetContainer(env string) *Container {
	configConfig := config.InitConfig(env)
	iAuthService := service.NewAuthService()
	container := NewContainer(configConfig, iAuthService)
	return container
}
