// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/li1553770945/sheepim-auth-service/biz/infra/config"
	"github.com/li1553770945/sheepim-auth-service/biz/infra/rpc"
	"github.com/li1553770945/sheepim-auth-service/biz/internal/service"
)

// Injectors from wire.go:

func GetContainer(cfg *config.Config) *Container {
	secretKeys := config.GetSecretKey()
	client := rpc.NewUserClient(cfg)
	iAuthService := service.NewAuthService(client, secretKeys)
	container := NewContainer(cfg, secretKeys, iAuthService)
	return container
}
