// Code generated by Kitex v0.7.2. DO NOT EDIT.

package authservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	auth "github.com/li1553770945/sheepim-auth-service/kitex_gen/auth"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Login(ctx context.Context, req *auth.LoginReq, callOptions ...callopt.Option) (r *auth.LoginResp, err error)
	Logout(ctx context.Context, req *auth.LogoutReq, callOptions ...callopt.Option) (r *auth.LogoutResp, err error)
	GenerateActiveCode(ctx context.Context, req *auth.GenerateActiveCodeReq, callOptions ...callopt.Option) (r *auth.GenerateActiveCodeResp, err error)
	Register(ctx context.Context, req *auth.RegisterReq, callOptions ...callopt.Option) (r *auth.RegisterResp, err error)
	GetUserId(ctx context.Context, req *auth.GetUserIdReq, callOptions ...callopt.Option) (r *auth.GetUserIdResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAuthServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAuthServiceClient struct {
	*kClient
}

func (p *kAuthServiceClient) Login(ctx context.Context, req *auth.LoginReq, callOptions ...callopt.Option) (r *auth.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kAuthServiceClient) Logout(ctx context.Context, req *auth.LogoutReq, callOptions ...callopt.Option) (r *auth.LogoutResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Logout(ctx, req)
}

func (p *kAuthServiceClient) GenerateActiveCode(ctx context.Context, req *auth.GenerateActiveCodeReq, callOptions ...callopt.Option) (r *auth.GenerateActiveCodeResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GenerateActiveCode(ctx, req)
}

func (p *kAuthServiceClient) Register(ctx context.Context, req *auth.RegisterReq, callOptions ...callopt.Option) (r *auth.RegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kAuthServiceClient) GetUserId(ctx context.Context, req *auth.GetUserIdReq, callOptions ...callopt.Option) (r *auth.GetUserIdResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserId(ctx, req)
}
